### ISSUE TITLE
Fails to run: global name 'dispAdjConv' is not defined

### ISSUE THREAD

**Issue by jfreimer** [ratschlab/RiboDiff#1]
Start the statistical test.
100 genes finished.. 
Testing statistical test: Done.

---

Testing calculate TE and fold change: Done.

---

Traceback (most recent call last):
  File "src/ribodiff/functional_test_te.py", line 90, in <module>
    main()
  File "src/ribodiff/functional_test_te.py", line 61, in main
    wr.write_result(data, opts)
  File "/N/home/j/f/jfreimer/Mason/RiboDiff-master/src/ribodiff/writeres.py", line 35, in write_result
    outNdarrayUnsorted = np.hstack([geneIDs, dispAdj, dispAdjConv, pval, padj, TEctl, TEtrt, logFoldChangeTE])
NameError: global name 'dispAdjConv' is not defined
Error running test cases.
Exit status return code = 1
ERROR
# 
## ERROR: testTransEfficiency (tests.TE_test.TransEfficiency)

Traceback (most recent call last):
  File "/N/home/j/f/jfreimer/Mason/RiboDiff-master/tests/TE_test.py", line 36, in testTransEfficiency
    sys.exit(0)
SystemExit: 0

---

Ran 1 test in 28.166s

FAILED (errors=1)

**Comment by yizhong** [comment]
Thanks for catching. Issue fixed.
Please pull the latest code and try again.

**Comment by jfreimer** [comment]
Thanks it ran fine now.
